### ISSUE TITLE
`contented-extra`

### ISSUE THREAD

**Issue by fuxingloh** [levaintech/contented#62]
#### What would you like to be added:

- [ ] Parse `js/ts` documentations into Markdown into HTML
- [x] Parse `jest` documentations/comments into Markdown into HTML (Better DX, instead of parsing markdown into jest)
- [ ] Parse `GRPC` documentations/comments into Markdown into HTM

#### Why is this needed:

Contextual documentations.

/triage accepted
/area contented-processor

**Comment by cwkang1998** [comment]
Would love to work on `js/ts` documentation, if its not being worked on right now?

**Comment by fuxingloh** [comment]
> Would love to work on `js/ts` documentation, if its not being worked on right now?

Right now it's quite a low priority given that we don't really have a use case for that yet. Since the focus is more on shift-left consumer-facing documentation instead of internal technical docs.
